<a href="https://colab.research.google.com/github/hanafarahd/20051397073-PRAKTIKUM-5/blob/main/Tugas_Akhir_Sistem_Prediksi_Data_Piutang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Modul + Library

In [ ]:
import numpy as np
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import plotly.graph_objs as go
import plotly.tools as tls
from plotly.offline import iplot, init_notebook_mode
import seaborn as sns

from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
import category_encoders as ce
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
!pip install category_encoders

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 2.2 MB/s eta 0:00:00


In [ ]:
!pip install --upgrade scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 69.8 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


# Mount dataset dari Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_excel('/content/Aging Ar + Tracking DO Okt 2022 SURABAYA.xlsx')

In [ ]:
path= '/content/Aging Ar + Tracking DO Okt 2022 SURABAYA.xlsx'

df_dataset = pd.read_excel(path)

In [ ]:
df

Customer Code  Customer X             Customer Name Trans Date  \
0        C10-00002     Reguler   2 OSCAR APT. (SURABAYA) 2022-10-06   
1        C10-00002     Reguler   2 OSCAR APT. (SURABAYA) 2022-10-07   
2        C10-00012     Reguler      AGRIPA APT(SURABAYA) 2022-10-07   
3        C10-00016     Reguler           BONNET SWALAYAN 2022-09-12   
4        C10-00029     Reguler     ALISA APT. (MOJOARUM) 2022-09-12   
...            ...         ...                       ...        ...   
7633     C10-X6243  Customer X  PT.HERO SUPERMARKET TBK. 2016-03-31   
7634     C10-X6243  Customer X  PT.HERO SUPERMARKET TBK. 2016-03-31   
7635     C10-X6243  Customer X  PT.HERO SUPERMARKET TBK. 2016-03-31   
7636     C10-X6243  Customer X  PT.HERO SUPERMARKET TBK. 2016-03-31   
7637     C10-X9999  Customer X           CUSTOMER X 2018 2018-12-31   

       Nomor Faktur Pajak Invoice    Voucher Type Jual Kode Salesman  \
0     010.008-22.04800051  821043     777683   Reguler             4   
1     010.008-22.04800198  821372     777830   Reguler             4   
2     010.008-22.04800174  821237     777806   Reguler             4   
3     010.008-22.04797213  818011     774846   Reguler            68   
4     010.008-22.04797278  818252     774911   Reguler            45   
...                   ...     ...        ...       ...           ...   
7633                  NaN     NaN  MJ.022243   Reguler         RP001   
7634                  NaN     NaN  MJ.022254   Reguler         RP001   
7635                  NaN     NaN  MJ.022257   Reguler         RP001   
7636                  NaN     NaN  MJ.022259   Reguler         RP001   
7637                  NaN     NaN  MJ.039396   Reguler         RP001   

           Nama Salesman  ...     Nama Territory   Due Date  Invoice Amount  \
0      Geger Harianto S.  ...  Surabaya Tengah 1 2022-10-27       823173.78   
1      Geger Harianto S.  ...  Surabaya Tengah 1 2022-10-28       318792.00   
2      Geger Harianto S.  ...  Surabaya Tengah 1 2022-10-14       594738.00   
3     Amilatatus Solecha  ...   Surabaya Timur 2 2022-10-03      1070040.00   
4            Kokok Teguh  ...   Surabaya Timur 1 2022-10-03       378674.28   
...                  ...  ...                ...        ...             ...   
7633     Reclass Piutang  ...  Surabaya Tengah 2 2014-02-07       114400.00   
7634     Reclass Piutang  ...  Surabaya Tengah 2 2014-04-29        57200.00   
7635     Reclass Piutang  ...  Surabaya Tengah 2 2014-05-20        76808.00   
7636     Reclass Piutang  ...  Surabaya Tengah 2 2014-06-20        68031.00   
7637     Reclass Piutang  ...  Surabaya Tengah 1 2018-12-31       -70856.34   

     Settlement Outstanding AR  Cut Off Date  Umur Piutang ( Hari )  Aging  \
0           0.0      823173.78    2022-10-18                     12    ≤30   
1           0.0      318792.00    2022-10-18                     11    ≤30   
2           0.0      594738.00    2022-10-18                     11    ≤30   
3     1060000.0       10040.00    2022-10-18                     36  31-60   
4      378674.0           0.28    2022-10-18                     36  31-60   
...         ...            ...           ...                    ...    ...   
7633        0.0      114400.00    2022-10-18                   2392   >120   
7634        0.0       57200.00    2022-10-18                   2392   >120   
7635        0.0       76808.00    2022-10-18                   2392   >120   
7636        0.0       68031.00    2022-10-18                   2392   >120   
7637        0.0      -70856.34    2022-10-18                   1387   >120   

        Cabang  Durasi Keterlambatan  
0     Surabaya                  -9.0  
1     Surabaya                 -10.0  
2     Surabaya                   4.0  
3     Surabaya                  15.0  
4     Surabaya                  15.0  
...        ...                   ...  
7633  Surabaya                   NaN  
7634  Surabaya                   NaN  
7635  Surabaya                   NaN  
7636  Surab

# Persiapan Data

In [ ]:
df.rename(columns={
    'Customer Code':'Customer_Code',
    'Customer X':'Customer_X',
    'Customer Name':'Customer_Name',
    'Trans Date':'Trans_Date',
    'Nomor Faktur Pajak':'Nomor_Faktur_Pajak',
    'Type Jual':'Type_Jual',
    'Kode Salesman':'Kode_Salesman',
    'Nama Salesman':'Nama_Salesman',
    'CustGroup Name':'CustGroupName',
    'Kode Territory':'Kode_Territory',
    'Nama Territory':'Nama_Territory',
    'Due Date':'Due_Date',
    'Invoice Amount':'Invoice_Amount',
    'Outstanding AR':'Outstanding_AR',
    'Cut Off Date':'Cutoff_Date',
    'Umur Piutang (Hari)':'Umur_Piutang(Hari)',
    'Durasi Keterlambatan':'Durasi_Keterlambatan'
},inplace=True)

print(df)

     Customer_Code  Customer_X             Customer_Name Trans_Date  \
0        C10-00002     Reguler   2 OSCAR APT. (SURABAYA) 2022-10-06   
1        C10-00002     Reguler   2 OSCAR APT. (SURABAYA) 2022-10-07   
2        C10-00012     Reguler      AGRIPA APT(SURABAYA) 2022-10-07   
3        C10-00016     Reguler           BONNET SWALAYAN 2022-09-12   
4        C10-00029     Reguler     ALISA APT. (MOJOARUM) 2022-09-12   
...            ...         ...                       ...        ...   
7633     C10-X6243  Customer X  PT.HERO SUPERMARKET TBK. 2016-03-31   
7634     C10-X6243  Customer X  PT.HERO SUPERMARKET TBK. 2016-03-31   
7635     C10-X6243  Customer X  PT.HERO SUPERMARKET TBK. 2016-03-31   
7636     C10-X6243  Customer X  PT.HERO SUPERMARKET TBK. 2016-03-31   
7637     C10-X9999  Customer X           CUSTOMER X 2018 2018-12-31   

       Nomor_Faktur_Pajak Invoice    Voucher Type_Jual Kode_Salesman  \
0     010.008-22.04800051  821043     777683   Reguler             4   
1  

In [ ]:
df.shape

(7638, 23)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7638 entries, 0 to 7637
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   Customer_Code          7638 non-null   object        
 1   Customer_X             7638 non-null   object        
 2   Customer_Name          7638 non-null   object        
 3   Trans_Date             7638 non-null   datetime64[ns]
 4   Nomor_Faktur_Pajak     6213 non-null   object        
 5   Invoice                6842 non-null   object        
 6   Voucher                7638 non-null   object        
 7   Type_Jual              7638 non-null   object        
 8   Kode_Salesman          7638 non-null   object        
 9   Nama_Salesman          7592 non-null   object        
 10  CustGroup              7638 non-null   object        
 11  CustGroupName          7638 non-null   object        
 12  Kode_Territory         7638 non-null   int64         
 13  Nam

In [ ]:
df.isnull().sum()

Customer_Code               0
Customer_X                  0
Customer_Name               0
Trans_Date                  0
Nomor_Faktur_Pajak       1425
Invoice                   796
Voucher                     0
Type_Jual                   0
Kode_Salesman               0
Nama_Salesman              46
CustGroup                   0
CustGroupName               0
Kode_Territory              0
Nama_Territory              0
Due_Date                   38
Invoice_Amount              0
Settlement                  0
Outstanding_AR              0
Cutoff_Date                 0
Umur Piutang ( Hari )       0
Aging                       0
Cabang                      0
Durasi_Keterlambatan      654
dtype: int64

# Cleaning Data

In [ ]:
df = df.dropna()

In [ ]:
df.isnull().sum()

Customer_Code            0
Customer_X               0
Customer_Name            0
Trans_Date               0
Nomor_Faktur_Pajak       0
Invoice                  0
Voucher                  0
Type_Jual                0
Kode_Salesman            0
Nama_Salesman            0
CustGroup                0
CustGroupName            0
Kode_Territory           0
Nama_Territory           0
Due_Date                 0
Invoice_Amount           0
Settlement               0
Outstanding_AR           0
Cutoff_Date              0
Umur Piutang ( Hari )    0
Aging                    0
Cabang                   0
Durasi_Keterlambatan     0
dtype: int64

In [ ]:
df.head()

Customer_Code Customer_X            Customer_Name Trans_Date  \
0     C10-00002    Reguler  2 OSCAR APT. (SURABAYA) 2022-10-06   
1     C10-00002    Reguler  2 OSCAR APT. (SURABAYA) 2022-10-07   
2     C10-00012    Reguler     AGRIPA APT(SURABAYA) 2022-10-07   
3     C10-00016    Reguler          BONNET SWALAYAN 2022-09-12   
4     C10-00029    Reguler    ALISA APT. (MOJOARUM) 2022-09-12   

    Nomor_Faktur_Pajak Invoice Voucher Type_Jual Kode_Salesman  \
0  010.008-22.04800051  821043  777683   Reguler             4   
1  010.008-22.04800198  821372  777830   Reguler             4   
2  010.008-22.04800174  821237  777806   Reguler             4   
3  010.008-22.04797213  818011  774846   Reguler            68   
4  010.008-22.04797278  818252  774911   Reguler            45   

        Nama_Salesman  ...     Nama_Territory   Due_Date  Invoice_Amount  \
0   Geger Harianto S.  ...  Surabaya Tengah 1 2022-10-27       823173.78   
1   Geger Harianto S.  ...  Surabaya Tengah 1 2022-10-28       318792.00   
2   Geger Harianto S.  ...  Surabaya Tengah 1 2022-10-14       594738.00   
3  Amilatatus Solecha  ...   Surabaya Timur 2 2022-10-03      1070040.00   
4         Kokok Teguh  ...   Surabaya Timur 1 2022-10-03       378674.28   

  Settlement Outstanding_AR  Cutoff_Date  Umur Piutang ( Hari )  Aging  \
0        0.0      823173.78   2022-10-18                     12    ≤30   
1        0.0      318792.00   2022-10-18                     11    ≤30   
2        0.0      594738.00   2022-10-18                     11    ≤30   
3  1060000.0       10040.00   2022-10-18                     36  31-60   
4   378674.0           0.28   2022-10-18                     36  31-60   

     Cabang  Durasi_Keterlambatan  
0  Surabaya                  -9.0  
1  Surabaya                 -10.0  
2  Surabaya                   4.0  
3  Surabaya                  15.0  
4  Surabaya                  15.0  

[5 rows x 23 columns]

In [ ]:
df.shape

(6213, 23)

# Transform Data

In [ ]:
# Konversi kolom tanggal menjadi tipe data Date
df['Trans_Date'] = pd.to_datetime(df['Trans_Date'])
df['Trans_DateOnly'] = df['Trans_Date'].dt.date
df['Due_Date'] = pd.to_datetime(df['Due_Date'])
df['Due_DateOnly'] = df['Due_Date'].dt.date
df['Cutoff_Date'] = pd.to_datetime(df['Cutoff_Date'])
df['Cutoff_DateOnly']= df['Cutoff_Date'].dt.date

<ipython-input-16-fd522ad1ecc3>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-16-fd522ad1ecc3>:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-16-fd522ad1ecc3>:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-16-fd522ad

In [ ]:
print(df['Due_DateOnly'])

0       2022-10-27
1       2022-10-28
2       2022-10-14
3       2022-10-03
4       2022-10-03
           ...    
6971    2022-10-31
6972    2022-09-26
6974    2022-10-07
6975    2022-10-07
6976    2022-10-17
Name: Due_DateOnly, Length: 6213, dtype: object


In [ ]:
# Setelah itu, Anda dapat mengakses komponen tanggal
df['Trans_DateMonth'] = df['Trans_Date'].dt.month / 12
df['Trans_DateDay'] = df['Trans_Date'].dt.day / 31
df['Due_DateMonth'] = df['Due_Date'].dt.month / 12
df['Due_DateDay'] = df['Due_Date'].dt.day / 31

<ipython-input-18-6d2a0275a595>:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-18-6d2a0275a595>:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-18-6d2a0275a595>:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-18-6d2a027

In [ ]:
df.describe().T.style.set_properties(**{'background-color':'grey','color':'white','border-color':'white'})

In [ ]:
def aging_category(Aging):
  if Aging == '≤30' :
    return 1
  elif Aging == '31-60':
          return 2
  elif Aging == '61-90':
          return 3
  elif Aging == '91-120':
          return 4
  if Aging == '>120' :
          return 5
  else:
    return 0

In [ ]:
df['Aging'] = df['Aging'].apply(aging_category)

<ipython-input-21-6cd91429f882>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [ ]:
print(df)

     Customer_Code Customer_X                Customer_Name Trans_Date  \
0        C10-00002    Reguler      2 OSCAR APT. (SURABAYA) 2022-10-06   
1        C10-00002    Reguler      2 OSCAR APT. (SURABAYA) 2022-10-07   
2        C10-00012    Reguler         AGRIPA APT(SURABAYA) 2022-10-07   
3        C10-00016    Reguler              BONNET SWALAYAN 2022-09-12   
4        C10-00029    Reguler        ALISA APT. (MOJOARUM) 2022-09-12   
...            ...        ...                          ...        ...   
6971     C10-99090    Reguler                    NURHAYATI 2022-10-10   
6972     C10-99118    Reguler  MUCHAMMAD MASTUR ISDYANTORO 2022-09-19   
6974     C10-99118    Reguler  MUCHAMMAD MASTUR ISDYANTORO 2022-09-30   
6975     C10-99118    Reguler  MUCHAMMAD MASTUR ISDYANTORO 2022-09-30   
6976     C10-99118    Reguler  MUCHAMMAD MASTUR ISDYANTORO 2022-10-10   

       Nomor_Faktur_Pajak Invoice Voucher Type_Jual Kode_Salesman  \
0     010.008-22.04800051  821043  777683   Reguler   

In [ ]:
def Late_Category(Durasi_Keterlambatan):
    if Durasi_Keterlambatan > 0 :
        return 1


    else:
        return 0  # Default value jika tidak memenuhi kriteria di atas

In [ ]:
df['Late_Category'] = df['Durasi_Keterlambatan'].apply(Late_Category)

<ipython-input-24-0da0c876a934>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [ ]:
print(df)

     Customer_Code Customer_X                Customer_Name Trans_Date  \
0        C10-00002    Reguler      2 OSCAR APT. (SURABAYA) 2022-10-06   
1        C10-00002    Reguler      2 OSCAR APT. (SURABAYA) 2022-10-07   
2        C10-00012    Reguler         AGRIPA APT(SURABAYA) 2022-10-07   
3        C10-00016    Reguler              BONNET SWALAYAN 2022-09-12   
4        C10-00029    Reguler        ALISA APT. (MOJOARUM) 2022-09-12   
...            ...        ...                          ...        ...   
6971     C10-99090    Reguler                    NURHAYATI 2022-10-10   
6972     C10-99118    Reguler  MUCHAMMAD MASTUR ISDYANTORO 2022-09-19   
6974     C10-99118    Reguler  MUCHAMMAD MASTUR ISDYANTORO 2022-09-30   
6975     C10-99118    Reguler  MUCHAMMAD MASTUR ISDYANTORO 2022-09-30   
6976     C10-99118    Reguler  MUCHAMMAD MASTUR ISDYANTORO 2022-10-10   

       Nomor_Faktur_Pajak Invoice Voucher Type_Jual Kode_Salesman  \
0     010.008-22.04800051  821043  777683   Reguler   

In [ ]:
print(df['Late_Category'].value_counts())

Late_Category
1    3696
0    2517
Name: count, dtype: int64


In [ ]:
columns_keep = ['Due_Date', 'Trans_Date', 'Cutoff_Date', 'Late_Category']

df = df.drop(columns=[col for col in df.columns if col not in columns_keep])
print(df)

     Trans_Date   Due_Date Cutoff_Date  Late_Category
0    2022-10-06 2022-10-27  2022-10-18              0
1    2022-10-07 2022-10-28  2022-10-18              0
2    2022-10-07 2022-10-14  2022-10-18              1
3    2022-09-12 2022-10-03  2022-10-18              1
4    2022-09-12 2022-10-03  2022-10-18              1
...         ...        ...         ...            ...
6971 2022-10-10 2022-10-31  2022-10-18              0
6972 2022-09-19 2022-09-26  2022-10-18              1
6974 2022-09-30 2022-10-07  2022-10-18              1
6975 2022-09-30 2022-10-07  2022-10-18              1
6976 2022-10-10 2022-10-17  2022-10-18              1

[6213 rows x 4 columns]


In [ ]:
df['Trans_Month'] = df['Trans_Date'].dt.month
df['Trans_Day'] = df['Trans_Date'].dt.day
df['Trans_Year'] = df['Trans_Date'].dt.year

df['Due_Month'] = df['Due_Date'].dt.month
df['Due_Day'] = df['Due_Date'].dt.day
df['Due_Year'] = df['Due_Date'].dt.year

df['Cutoff_Month'] = df['Cutoff_Date'].dt.month
df['Cutoff_Day'] = df['Cutoff_Date'].dt.day
df['Cutoff_Year'] = df['Cutoff_Date'].dt.year

In [ ]:
columns_drop = ['Due_Date', 'Trans_Date', 'Cutoff_Date']

df = df.drop(columns=[col for col in df.columns if col in columns_drop])
print(df)

      Late_Category  Trans_Month  Trans_Day  Trans_Year  Due_Month  Due_Day  \
0                 0           10          6        2022         10       27   
1                 0           10          7        2022         10       28   
2                 1           10          7        2022         10       14   
3                 1            9         12        2022         10        3   
4                 1            9         12        2022         10        3   
...             ...          ...        ...         ...        ...      ...   
6971              0           10         10        2022         10       31   
6972              1            9         19        2022          9       26   
6974              1            9         30        2022         10        7   
6975              1            9         30        2022         10        7   
6976              1           10         10        2022         10       17   

      Due_Year  Cutoff_Month  Cutoff_Day  Cutoff_Ye

In [ ]:
X = df.iloc[:, 1:].values
Y = df.iloc[:, 0].values

In [ ]:
X.shape

(6213, 9)

In [ ]:
Y.shape

(6213,)

In [ ]:
X

array([[  10,    6, 2022, ...,   10,   18, 2022],
       [  10,    7, 2022, ...,   10,   18, 2022],
       [  10,    7, 2022, ...,   10,   18, 2022],
       ...,
       [   9,   30, 2022, ...,   10,   18, 2022],
       [   9,   30, 2022, ...,   10,   18, 2022],
       [  10,   10, 2022, ...,   10,   18, 2022]], dtype=int32)

In [ ]:
Y

array([0, 0, 1, ..., 1, 1, 1])

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
X_train

array([[   5,   18, 2021, ...,   10,   18, 2022],
       [   9,   14, 2016, ...,   10,   18, 2022],
       [  10,   24, 2017, ...,   10,   18, 2022],
       ...,
       [  10,   17, 2022, ...,   10,   18, 2022],
       [   9,   23, 2022, ...,   10,   18, 2022],
       [   6,    8, 2018, ...,   10,   18, 2022]], dtype=int32)

In [ ]:
X_test

array([[  10,   17, 2017, ...,   10,   18, 2022],
       [  10,   12, 2022, ...,   10,   18, 2022],
       [   2,   23, 2018, ...,   10,   18, 2022],
       ...,
       [   9,    8, 2022, ...,   10,   18, 2022],
       [   9,   23, 2022, ...,   10,   18, 2022],
       [   9,   28, 2022, ...,   10,   18, 2022]], dtype=int32)

In [ ]:
X_train.shape

(4970, 9)

In [ ]:
Y_train.shape

(4970,)

In [ ]:
Y_train

array([1, 1, 1, ..., 0, 1, 1])

In [ ]:
Y_test

array([1, 0, 1, ..., 0, 1, 0])

# Metode Naive Bayes

In [ ]:
nb_clf = GaussianNB()

In [ ]:
nb_clf.fit(X_train, Y_train)

GaussianNB()

In [ ]:
nb_y_pred = nb_clf.predict(X_test)

In [ ]:
nb_accuracy = accuracy_score(Y_test, nb_y_pred)
print("Naive Bayes Accuracy:", nb_accuracy)

Naive Bayes Accuracy: 0.6218825422365245


In [ ]:
print(nb_y_pred)

[1 0 1 ... 0 0 0]


In [ ]:
# Buat DataFrame untuk membandingkan hasil prediksi dengan hasil sebenarnya
comparison_df = pd.DataFrame({
    'Hasil Sebenarnya': Y_test,
    'Hasil Prediksi': nb_y_pred,
})

# Tampilkan beberapa baris pertama dari DataFrame untuk melihat perbandingan
print(comparison_df)

      Hasil Sebenarnya  Hasil Prediksi
0                    1               1
1                    0               0
2                    1               1
3                    1               0
4                    1               1
...                ...             ...
1238                 1               0
1239                 1               0
1240                 0               0
1241                 1               0
1242                 0               0

[1243 rows x 2 columns]


# Kombinasi Metode Naive Bayes dan K-Nearest Neighbors

In [ ]:
knn_clf = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn_clf.fit(X_train, Y_train)

KNeighborsClassifier()

In [ ]:
knn_y_pred = knn_clf.predict(X_test)
nb_y_pred = nb_clf.predict(X_test)

In [ ]:
combined_y_pred = []

for knn_pred, nb_pred in zip(knn_y_pred, nb_y_pred):
    # Jika salah satu prediksi nol, gunakan prediksi dari model lainnya
    if knn_pred == 0:
        combined_y_pred.append(int(nb_pred))
    elif nb_pred == 0:
        combined_y_pred.append(int(knn_pred))
    else:
        # Jika kedua prediksi tidak nol, gunakan rata-rata dari keduanya
        combined_y_pred.append(int((knn_pred + nb_pred) / 2))

In [ ]:
combined_accuracy = accuracy_score(Y_test, combined_y_pred)

print("Combined Accuracy:", combined_accuracy)

Combined Accuracy: 0.9919549477071601


In [ ]:
# Buat DataFrame untuk membandingkan hasil prediksi dengan hasil sebenarnya
comparison_df = pd.DataFrame({
    'Hasil Sebenarnya': Y_test,
    'Hasil Prediksi': combined_y_pred,
})

# Tampilkan beberapa baris pertama dari DataFrame untuk melihat perbandingan
print(comparison_df)

      Hasil Sebenarnya  Hasil Prediksi
0                    1               1
1                    0               0
2                    1               1
3                    1               1
4                    1               1
...                ...             ...
1238                 1               1
1239                 1               1
1240                 0               0
1241                 1               1
1242                 0               0

[1243 rows x 2 columns]


In [ ]:
precision = precision_score(Y_test, combined_y_pred)

recall = recall_score(Y_test, combined_y_pred)

conf_matrix = confusion_matrix(Y_test, combined_y_pred)

TP = conf_matrix[1, 1]
TN = conf_matrix[0, 0]
FP = conf_matrix[0, 1]
FN = conf_matrix[1, 0]

z_score = (precision - 0.5) / ((precision * (1 - precision) / len(Y_test)) ** 0.5)

print("Precision:", precision)
print("Recall:", recall)
print("Z-score:", z_score)

Precision: 0.9985935302390999
Recall: 0.9874826147426982
Z-score: 469.0537684275278


# Pelatihan Model Klasifikasi Dengan Kombinasi Antara Naive Bayes dan K-Neirest Neighbors

In [ ]:
import joblib
from sklearn.ensemble import VotingClassifier

nb = GaussianNB()
knn = KNeighborsClassifier()

combined_model = VotingClassifier(estimators=[
    ('knn', knn),
    ('nb', nb)
], voting='soft')

combined_model.fit(X_train, Y_train)

joblib.dump(combined_model, 'model_piutang.pkl')
print("Model Piutang disimpan.")

Model Piutang disimpan.


In [ ]:
import flask
from flask import Flask, request, jsonify
import joblib
import warnings
warnings.filterwarnings('ignore')


app = Flask(__name__)
model_piutang = joblib.load('model_piutang.pkl', mmap_mode='r')

def combined_y_pred(data):
    # Lakukan prediksi piutang
    return model_piutang.predict(data)

@app.route('/predict', methods=['POST'])
def predict():
    data = request.json

    # Konversi nilai data menjadi bilangan bulat
    # data_int = [int(value) for value in data.values()]

    # Lakukan prediksi untuk ketiga model
    piutang_prediction = combined_y_pred([data])

    def convert_to_label_piutang(prediction):
        return "Terlambat" if prediction == 1 else "Tidak Terlambat"

    # Konversi hasil prediksi menjadi label yang lebih mudah dibaca
    piutang_label = convert_to_label_piutang(piutang_prediction)

    # Kembalikan hasil prediksi untuk ketiga model dalam satu respons JSON
    predictions = {
        'Hasil Prediksi Piutang': piutang_label
    }

    return jsonify(predictions)
if __name__ == '__main__':
    app.run(debug=True)

 * Serving Flask app '__main__'
 * Debug mode: on


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat
